/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.uramnoil.prometheus.papermc

import io.prometheus.client.exporter.HTTPServer
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.receiveAsFlow
import org.bukkit.event.EventHandler
import org.bukkit.event.Listener
import org.bukkit.event.player.PlayerJoinEvent
import org.bukkit.event.player.PlayerQuitEvent
import org.bukkit.plugin.java.JavaPlugin
import java.util.logging.Level

@Suppress("unused")
class PapermcExporter : JavaPlugin(), Listener{
    private val metrics = ServerMetrics()
    private val closeChannel = Channel<Unit>()
    private lateinit var httpServer: HTTPServer

    override fun onEnable() {
        server.pluginManager.registerEvents(this, this)

        // Run Prometheus Exporter
        logger.info("Starting prometheus exporter server")
        httpServer = HTTPServer.Builder().withPort(9100).withDaemonThreads(true).build()
    }

    override fun onDisable() {
        httpServer.close()
    }

    @EventHandler
    fun onPlayerJoin(event: PlayerJoinEvent) {
        metrics.onPlayerJoin()
    }

    @EventHandler
    fun onPlayerExit(event: PlayerQuitEvent) {
        metrics.onPlayerQuit()
    }
}
